### ISSUE TITLE
Connect BackEnd to DB

### ISSUE THREAD

**Issue by zchemali** [ca-west-1/web-development-project-ensf-607#28]
Connect BackEnd to MYSQL and write Queries to insert/extract info from DB

**Comment by stancsz** [comment]
![image](https://user-images.githubusercontent.com/43565411/103451184-06497600-4c7e-11eb-8200-50483ce101c3.png)
connected django to backend db
![image](https://user-images.githubusercontent.com/43565411/103451187-106b7480-4c7e-11eb-9d46-3ada879c79d9.png)
next step is to model the tables

**Comment by stancsz** [comment]
backend models are now connected to mysql database
![image](https://user-images.githubusercontent.com/43565411/103479128-bc998200-4d88-11eb-9fe0-45b9c4095e95.png)
