### ISSUE TITLE
Course-information

### ISSUE THREAD

**Issue by zchemali** [ca-west-1/web-development-project-ensf-607#9]
Create the course information section and add it to the front-end template 
This belongs to #7

**Comment by hasnil** [comment]
December 17 2020
Problems faced: 
Challenging understanding state, json objects, props, how to connect different parts of application with dynamic behavior.

What I have done:
Slight changes to course info section, worked with json-server and react-admin.

What I will do:
Learn more about the connection between different files and frontend/backend.
